apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-apps
spec:
  generators:
  - git:
      repoURL: https://github.com/serdfxe/my-argo-app.git
      revision: main
      directories:
      - path: "apps/demo-app/k8s"
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/serdfxe/my-argo-app.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          selfHeal: true
          prune: true