name: Build and Push Demo App

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and Push
      run: |
        ls 
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/demo-app:${{ github.sha }} -f apps/demo-app/Dockerfile .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/demo-app:${{ github.sha }}
