name: Build and Push Demo App

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and Push
      run: |
        ls 
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/demo-app:${{ github.sha }} -f apps/demo-app/Dockerfile .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/demo-app:${{ github.sha }}
        
    - name: Update k8s manifest
      run: |
        sed -i "s|image:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/demo-app:${{ github.sha }}|" apps/demo-app/k8s/deployment.yaml
        git config --global user.name "CI/CD Bot"
        git commit -am "Update demo-app image to ${{ github.sha }}"
        git push
