name: Deploy to Kubernetes

on:
  push:
    branches: [ main, master ]

env:
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-k8s-app
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-k8s-app -f Dockerfile .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-k8s-app

    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      
    - name: Configure Kubernetes
      run: |
        mkdir -p ~/.kube
        echo "$KUBE_CONFIG" > ~/.kube/config
        kubectl version --client

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml
