name: Deploy to Kubernetes

on:
  push:
    branches: [ main, master ]

env:
  DOCKER_IMAGE: ghcr.io/${{ github.repository_owner }}/fastapi-k8s-demo-app
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t $DOCKER_IMAGE:${{ github.sha }} -t $DOCKER_IMAGE:latest -f Dockerfile .
        docker push $DOCKER_IMAGE:${{ github.sha }}
        docker push $DOCKER_IMAGE:latest

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      
    - name: Configure Kubernetes
      run: |
        mkdir -p ~/.kube
        echo "$KUBE_CONFIG" > ~/.kube/config
        kubectl version --client

    - name: Update deployment manifest
      run: |
        sed -i "s|image: .*|image: $DOCKER_IMAGE:${{ github.sha }}|" kubernetes/deployment.yaml

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml
