name: Build and Push

on:
  push:
    branches: [ main, master ]

env:
  DOCKER_IMAGE: ghcr.io/${{ github.repository_owner }}/fastapi-k8s-demo-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t $DOCKER_IMAGE:${{ github.sha }} -t $DOCKER_IMAGE:latest -f Dockerfile .
        docker push $DOCKER_IMAGE:${{ github.sha }}
        docker push $DOCKER_IMAGE:latest

    - name: Update deployment manifest
      run: |
        sed -i "s|image: .*|image: $DOCKER_IMAGE:${{ github.sha }}|" kubernetes/deployment.yaml
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add kubernetes/deployment.yaml
        git commit -m "Update image to $DOCKER_IMAGE:${{ github.sha }}"

    - name: Push changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${GITHUB_REPOSITORY}.git
        git push
